apiVersion: v1
kind: Service
metadata:
  name: traefik-agent
  namespace: traefik-dashboard
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/part-of: traefik-log-dashboard
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: agent
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
