apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: traefik-dashboard
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/part-of: traefik-log-dashboard
data:
  PORT: "5000"
  TRAEFIK_LOG_DASHBOARD_ACCESS_PATH: "/logs/access.log"
  TRAEFIK_LOG_DASHBOARD_ERROR_PATH: "/logs/traefik.log"
  TRAEFIK_LOG_DASHBOARD_LOG_FORMAT: "json"
  TRAEFIK_LOG_DASHBOARD_SYSTEM_MONITORING: "true"
  TRAEFIK_LOG_DASHBOARD_MONITOR_INTERVAL: "2000"
  TRAEFIK_LOG_DASHBOARD_STREAM_BATCH_LINES: "400"
  TRAEFIK_LOG_DASHBOARD_STREAM_FLUSH_INTERVAL_MS: "1000"
  TRAEFIK_LOG_DASHBOARD_STREAM_MAX_CLIENTS: "50"
  TRAEFIK_LOG_DASHBOARD_STREAM_MAX_DURATION_SEC: "300"
  POSITION_FILE: "/data/.position"
