apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-dashboard
resources:
  - namespace.yaml
  - secret.yaml
  - configmap-agent.yaml
  - configmap-dashboard.yaml
  - agent-pvc.yaml
  - agent-deployment.yaml
  - agent-service.yaml
  - dashboard-pvc.yaml
  - dashboard-deployment.yaml
  - dashboard-service.yaml
  - ingressroute.yaml
