apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-auth
  namespace: traefik-dashboard
  labels:
    app.kubernetes.io/part-of: traefik-log-dashboard
type: Opaque
stringData:
  auth-token: "REPLACE_WITH_YOUR_TOKEN" # openssl rand -hex 32
